cfg: Track_2/configs/parameters/peg_insertion_v2_points.yaml
env:
  env_name: PegInsertionSimMarkerFLowEnvV2
  final_reward: 50
  insertion_depth_mm: 1.0
  marker_interval_range: [1.95, 2.15]
  marker_lose_tracking_probability: 0.01
  marker_pos_shift_range: [0.1, 0.1]
  marker_random_noise: 0.5
  marker_rotation_range: 0.1
  marker_translation_range: [1, 1]
  max_action_mm_deg: [1.0, 1.0, 1.0, 1.0]
  max_steps: 50
  no_render: false
  normalize: false
  params:
    allow_self_collision: false
    ccd_max_iters: 100
    ccd_slackness: 0.7
    ccd_tet_inversion_thres: 0.0
    ccd_thickness: 1e-06
    ee_classify_thres: 0.001
    ee_mollifier_thres: 0.001
    gripper_x_offset_mm: [-1, 1]
    gripper_z_offset_mm: [-10, -6]
    hole_friction: [0.0, 1.0]
    indentation_depth_mm: [0.5, 1.25]
    line_search_max_iters: 10
    peg_friction: [4.0, 15.0]
    sim_d_hat: 0.0001
    sim_eps_d: 0
    sim_eps_v: 0.01
    sim_kappa: 100.0
    sim_kappa_affine: 100000.0
    sim_kappa_con: 10000000000.0
    sim_solver_cg_error_frequency: 10
    sim_solver_cg_error_tolerance: 0
    sim_solver_cg_max_iters: 50
    sim_solver_newton_max_iters: 5
    sim_time_step: 0.1
    tac_density_l: 1000.0
    tac_density_r: 1000.0
    tac_elastic_modulus_l: [300000.0, 300000.0]
    tac_elastic_modulus_r: [300000.0, 300000.0]
    tac_friction: [50.0, 125.0]
    tac_poisson_ratio_l: [0.3, 0.3]
    tac_poisson_ratio_r: [0.3, 0.3]
    tac_sensor_meta_file: gelsight_mini_e430/meta_file
  peg_dist_z_diff_mm: 3.0
  peg_dist_z_mm: 6.0
  peg_hole_path_file: configs/peg_insertion/to_real_multihole_1shape.txt
  peg_theta_max_offset_deg: 10.0
  peg_x_max_offset_mm: 5.0
  peg_y_max_offset_mm: 5.0
  step_penalty: 0.8
  vision_params:
    gt_point_cloud: true
    max_points: 128
    render_mode: rast
    vision_type: [point_cloud]
no_render: false
policy:
  action_noise: 0.5
  batch_size: 128
  buffer_size: 5000
  gradient_steps: -1
  learning_rate: 0.0003
  learning_starts: 1000
  policy_delay: 2
  policy_kwargs:
    features_extractor_class: PointCloud
    features_extractor_kwargs:
      tac_kwargs: {batchnorm: false, out_dim: 64}
      vision_kwargs: {batchnorm: false, out_dim: 128, scale: 100}
    net_arch:
      pi: [256, 256]
      qf: [256, 256]
    share_features_extractor: false
  policy_name: TD3PolicyForPegInsertionV2
  target_noise_clip: 1
  target_policy_noise: 0.5
  train_freq: 2
train:
  algorithm_name: TD3
  checkpoint_every: 1000
  device: cuda
  emp: {}
  eval_freq: 1000
  gpu: 0
  log_interval: 10
  n_eval: 50
  name: peg_insertion_v2_points
  parallel: 1
  seed: 0
  total_timesteps: 5000
