cfg: Track_1/configs/parameters/long_open_lock.yaml
env:
  env_name: LongOpenLockRandPointFlowEnv-v1
  final_reward: 10
  key_x_max_offset: 10
  key_y_max_offset: 0
  key_z_max_offset: 0
  marker_interval_range: [1.95, 2.15]
  marker_lose_tracking_probability: 0.01
  marker_pos_shift_range: [0.1, 0.1]
  marker_random_noise: 0.5
  marker_rotation_range: 0.1
  marker_translation_range: [1, 1]
  max_action: [4.0, 2.0]
  max_steps: 50
  normalize: false
  params:
    allow_self_collision: false
    ccd_max_iters: 100
    ccd_slackness: 0.7
    ccd_tet_inversion_thres: 0.0
    ccd_thickness: 1e-06
    ee_classify_thres: 0.001
    ee_mollifier_thres: 0.001
    indentation_depth: [0.5, 1.25]
    key_friction: [0.2, 1.0]
    key_lock_path_file: configs/key_and_lock/key_lock.txt
    line_search_max_iters: 10
    lock_friction: [0.0, 1.0]
    sim_d_hat: 0.0001
    sim_eps_d: 0
    sim_eps_v: 0.001
    sim_kappa: 100.0
    sim_kappa_affine: 100000.0
    sim_kappa_con: 10000000000.0
    sim_solver_cg_error_frequency: 10
    sim_solver_cg_error_tolerance: 0
    sim_solver_cg_max_iters: 50
    sim_solver_newton_max_iters: 5
    sim_time_step: 0.2
    tac_density_l: 1000.0
    tac_density_r: 1000.0
    tac_elastic_modulus_l: [300000.0, 300000.0]
    tac_elastic_modulus_r: [300000.0, 300000.0]
    tac_friction: [50.0, 125.0]
    tac_poisson_ratio_l: [0.3, 0.3]
    tac_poisson_ratio_r: [0.3, 0.3]
    tac_sensor_meta_file: gelsight_mini_e430/meta_file
  sensor_offset_x_range_len: 2.0
  sensor_offset_z_range_len: 2.0
  step_penalty: 1
no_render: false
policy:
  action_noise: 0.5
  batch_size: 128
  buffer_size: 200000
  gradient_steps: -1
  learning_rate: 0.0003
  learning_starts: 2000
  policy_delay: 2
  policy_kwargs:
    net_arch:
      pi: [256, 256]
      qf: [256, 256]
    pointnet_batchnorm: false
    pointnet_in_dim: 4
    pointnet_layernorm: true
    pointnet_out_dim: 32
    use_relative_motion: true
    zero_init_output: true
  policy_name: TD3PolicyForLongOpenLockPointFlowEnv
  target_noise_clip: 1
  target_policy_noise: 0.5
  train_freq: 2
train:
  algorithm_name: TD3
  checkpoint_every: 2000
  device: cuda
  emp: {}
  eval_freq: 2000
  gpu: 0
  log_interval: 10
  n_eval: 50
  name: long_open_lock
  parallel: 1
  seed: 0
  total_timesteps: 300000
  wandb_name: wandb_long_open_lock
